context:
  name: sciline
  version: "25.11.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sciline-${{ version }}.tar.gz
  sha256: 0ef3d3a4d34b29556a3d8803566a6f5eed5bfd5ca88112aaa04954c58bdb8434

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - cyclebane >=24.06.0
    - typing_extensions

tests:
  - python:
      imports:
        - sciline
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Build scientific pipelines for your data
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/sciline
  homepage: https://scipp.github.io/sciline/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
